# Generated by Django 5.2.12 on 2026-03-07 19:20

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=django_mongodb_backend.fields.ObjectIdAutoField(
                primary_key=True, serialize=False
            ),
        ),
    ]
