# Generated by Django 5.2.12 on 2026-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailotp",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
