# Generated by Django 5.2.12 on 2026-03-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
